# This is a basic workflow to help you get started with Actions

name: automation-challenge-postman-api

# Controls when the workflow will run
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Install Newman
      - name: npm install -g newmanD
        run: newman run benefits-dashboard-API.postman_collection.json -e dashboard-prod.postman_environment.json
        
      # Runs a single command using the runners shell
      - name: Run API Tests
        run: newman run benefits-dashboard-API.postman_collection.json -e dashboard-prod.postman_environment.json
